title: "QuantEcon — UFJF"
description: "Ciência de Dados e IA aplicados à Economia e Finanças"

remote_theme: just-the-docs/just-the-docs
plugins: [jekyll-remote-theme]

url: "https://pauloccoimbra.github.io"
baseurl: "/quantecon"

color_scheme: light

search_enabled: true
aux_links:
  "GitHub": https://github.com/pauloccoimbra/quantecon
aux_links_new_tab: true

permalink: pretty
sass: { style: compressed }

