title: "QuantEcon — UFJF"
description: "Ciência de Dados e IA aplicados à Economia e Finanças"

remote_theme: just-the-docs/just-the-docs
plugins: [jekyll-remote-theme]

url: "https://pauloccoimbra.github.io"
baseurl: "/quantecon"

color_scheme: light
search_enabled: true
nav_enabled: true   # garante que a navegação lateral está habilitada

# aux_links:
#  "GitHub": https://github.com/pauloccoimbra/quantecon
# aux_links_new_tab: true
